using System.Collections.Generic;
using Newtonsoft.Json;

namespace TBWArch.Archipelago;

public class ArchipelagoLocations
{
    const long BASE_ID = 1000;
    public static Dictionary<string, long> LocationNameToId = new Dictionary<string, long>
    {
        //Level completions
        {"Dream 2A|1 Zans Corridor|Official", 1030},
        {"Dream 2A|2 Zan Backup|Official", 1031},
        {"Dream 2A|3 Witchstorm|Official", 1032},
        {"Dream 2A|4 Whackadoor|Official", 1033},
        {"Dream 2B|1 Deconstruction|Official", 1034},
        {"Dream 2B|2 Go Jen|Official", 1035},
        {"Dream 2B|3 Barrels o Fun|Official", 1036},
        {"Dream 2B|4 The Grid|Official", 1037},
        {"Dream 2C|1  Ten Men|Official", 1038},
        {"Dream 2C|2 Double Dessa|Official", 1039},
        {"Dream 2C|3 Turret Parallel|Official", 1040},
        {"Dream 2D|1 Panic Rooms|Official", 1041},
        {"Dream 2D|3 The Race|Official", 1042},
        {"Dream 2D|4 Fire Closet|Official", 1043},
        {"Dream 3B|1 Judas Priests|Official", 1044},
        {"Dream 3B|2 Armoured Escort|Official", 1045},
        {"Dream 3B|3 Three Doors|Official", 1046},
        {"Dream 3C|1 The Cavalry|Official", 1047},
        {"Dream 3C|2 Reactor Recruiter|Official", 1048},
        {"Dream 3C|3 Push and Pull|Official", 1049},
        {"Dream 4A|1 Tough Cookie|Official", 1050},
        {"Dream 4A|2 Rocket Alley|Official", 1051},
        {"Dream 4A|3 Fortress|Official", 1052},
        {"Dream Heatsig|1 Warlocks in the Airlock|Official", 1053},
        {"Dream Heatsig|2 Sabotage|Official", 1054},
        {"Dream Heatsig|3 Escape Velocity|Official", 1055},
        {"Dream Intro|1 Warlock|Official", 1056},
        {"Evidence Boss|1 The Traffic Warlock|Official", 1057},
        {"Evidence Lockup|1 Lobby|Official", 1058},
        {"Evidence Lockup|2 Pillars|Official", 1059},
        {"Evidence Lockup|3 Corridors|Official", 1060},
        {"Exit Strategy|1 Entry Strategy|Official", 1061},
        {"Exit Strategy|2 Heavies|Official", 1062},
        {"Exit Strategy|3 Neutralisers|Official", 1063},
        {"Exit Strategy|4 Junction|Official", 1064},
        {"Finale - Mines|1 Dust To Dust|Official", 1065},
        {"Finale - Mines|2 The Motherlode|Official", 1066},
        {"Finale - Roof|1 Vesker s Landing|Official", 1067},
        {"Finale - Roof|2 The Black Ops Chronomancer|Official", 1068},
        {"Finale - Vault|1 The Gold Vault|Official", 1069},
        {"Finale - Vault|2 The Drop|Official", 1070},
        {"Flashback|1 Chokepoint|Official", 1071},
        {"Fort Osprey|1 Empty Coffins|Official", 1072},
        {"Fort Osprey|2 Cold Storage|Official", 1073},
        {"Fort Osprey|3 Shield Generators|Official", 1074},
        {"Fort Osprey|4 Fortified|Official", 1075},
        {"Kalan Ambush|1 Tick Tock|Official", 1076},
        {"Kalan Ambush 2|2 Liv And Let Die|Official", 1077},
        {"Liboli Intro|1 Twin Turrets|Official", 1078},
        {"Liboli Intro|2 Mainframe|Official", 1079},
        {"Liboli Intro|3 Heavy Duty|Official", 1080},
        {"Liboli Intro|4 The Cell|Official", 1081},
        {"Lucid Dream - Banks|1 The Body|Official", 1082},
        {"Lucid Dream - Banks|2 Passing On|Official", 1083},
        {"Lucid Dream - Banks|3 The Kill Zone|Official", 1084},
        {"Lucid Dream - Banks|4 Circle Of Death|Official", 1085},
        {"Lucid Dream - Banks|5 Resurrection Race|Official", 1086},
        {"Lucid Dream - Dall|1 Blind Faith|Official", 1087},
        {"Lucid Dream - Dall|2 The Hotspot|Official", 1088},
        {"Lucid Dream - Dall|3 Tunnel Rats|Official", 1089},
        {"Lucid Dream - Dall|4 Unstoppable Force|Official", 1090},
        {"Lucid Dream - Jen|1 Backdoor|Official", 1091},
        {"Lucid Dream - Jen|2 No Problem|Official", 1092},
        {"Lucid Dream - Jen|3 High Achiever|Official", 1093},
        {"Lucid Dream - Jen|4 Another Steve|Official", 1094},
        {"Lucid Dream - Rion|1 The Pit|Official", 1095},
        {"Lucid Dream - Rion|2 Arguably You Let The Dogs Out|Official", 1096},
        {"Lucid Dream - Rion|3 Anger Management|Official", 1097},
        {"Lucid Dream - Zan|1 Unsupportive Fire|Official", 1098},
        {"Lucid Dream - Zan|2 Beam Flower|Official", 1099},
        {"Lucid Dream - Zan|3 Mind Maze|Official", 1100},
        {"Lucid Dream - Zan|4 Bad Zan|Official", 1101},
        {"Prologue|1 Entry|Official", 1102},
        {"Prologue|2 Cover|Official", 1103},
        {"Prologue|3 Foresight|Official", 1104},
        {"Prologue|4 The Asset|Official", 1105},
        {"Proving Ground 1|1 The Clinic|Official", 1106},
        {"Proving Ground 2|1 The Cooker|Official", 1107},
        {"Proving Ground 3|1 The Wall|Official", 1108},
        {"Proving Ground 4|1 The Tank|Official", 1109},
        {"Siege Cleric|1 The Siege Cleric|Official", 1110},
        {"Siege Cleric|2 The Other Three Siege Clerics|Official", 1111},
        {"Streets|1 Downtown|Official", 1112},
        {"Streets|2 Curfew|Official", 1113},
        {"Streets|3 Going To Ground|Official", 1114},
        {"The Broadcast|1 Heavy Backup|Official", 1115},
        {"The Broadcast|2 Tipping Point|Official", 1116},
        {"The Broadcast|3 Firewall|Official", 1117},
        {"The Broadcast|4 Caught In Traffic|Official", 1118},
        {"The Broadcast|5 The Armoury|Official", 1119},
        {"The Meet|1 Spectral Skull|Official", 1120},
        {"The Meet|2 Officers|Official", 1121},
        {"The Meet|3 Reaching The Meet|Official", 1122},
        {"The Pyromancer|1 The Less Lethal Pyromancer|Official", 1123},
        {"The Recording|1 The Golden Arms|Official", 1124},
        {"The Recording|2 Protection Ring|Official", 1125},
        {"The Recording|3 The Dead Drop|Official", 1126},
        {"The Recording|4 The Stand|Official", 1127},
        {"Train|1 On Board|Official", 1128},
        {"Train|2 Sappers|Official", 1129},
        {"Train|3 The Shepherd|Official", 1130},
        {"Train|4 Terminal|Official", 1131},
        {"Train|5 The Riot Priest|Official", 1132},
        {"Two Trains|1 Gangway|Official", 1133},
        {"Two Trains|2 Barrier Drones|Official", 1134},
        {"Two Trains|3 Chasers|Official", 1135},
        {"Two Trains|4 Sabotage|Official", 1136},
        {"Two Trains|5 Countdown|Official", 1137},
        {"Villa Medil|1 Split Focus|Official", 1138},
        {"Villa Medil|2 Locked Out|Official", 1139},
        {"Villa Medil|3 Desk Job|Official", 1140},
        {"Villa Medil|4 Time Pressure|Official", 1141},
        {"Villa Medil|5 The Stone Table|Official", 1142},
        {"Witch Intro|1 Cross Purposes|Official", 1143},
        {"Witch Intro|2 Gunpoint Reunion|Official", 1144},
        {"Witch Intro|3 Positions|Official", 1145},
        {"Witch Intro|4 Self Fulfilling Prophecy|Official", 1146},
        {"Witch Intro|5 Predictive Predicament|Official", 1147},
        {"Witch Intro|6 Back for Banks|Official", 1148},
        {"Necro Intro|1 Intro|Official", 1149},
        {"Necro Intro|2 Lead Medicine|Official", 1150},
        {"Necro Intro|3 Broom Breach|Official", 1151},


        //Confidence goals
        {"Dream 2A|1 Zans Corridor|Official|PreventReinforcementsGoal", 1200},
        {"Dream 2A|2 Zan Backup|Official|PredictiveShotGoal", 1201},
        {"Dream 2A|3 Witchstorm|Official|FinishBeforeTurnGoal", 1202},
        {"Dream 2A|4 Whackadoor|Official|PreventReinforcementsGoal", 1203},
        {"Dream 2A|4 Whackadoor|Official|DefenestrateBeforeTurnGoal", 1204},
        {"Dream 2B|1 Deconstruction|Official|FinishBeforeTurnGoal", 1205},
        {"Dream 2B|1 Deconstruction|Official|SingleWizardActionsInOneTurnGoal", 1206},
        {"Dream 2B|2 Go Jen|Official|NoEnemiesFireGoal", 1207},
        {"Dream 2B|2 Go Jen|Official|WitchTotalKnockbackGoal", 1208},
        {"Dream 2B|3 Barrels o Fun|Official|AllWizardsAliveGoal", 1209},
        {"Dream 2B|3 Barrels o Fun|Official|DefenestrateBeforeTurnGoal", 1210},
        {"Dream 2B|4 The Grid|Official|AbilitiesInOneTurnGoal", 1211},
        {"Dream 2B|4 The Grid|Official|FinishBeforeTurnGoal", 1212},
        {"Dream 2C|1  Ten Men|Official|FinishBeforeTurnGoal", 1213},
        {"Dream 2C|1  Ten Men|Official|GhostShotHitGoal", 1214},
        {"Dream 2C|2 Double Dessa|Official|DeathsDoorTotalGoal", 1215},
        {"Dream 2C|3 Turret Parallel|Official|PreventReinforcementsGoal", 1216},
        {"Dream 2C|3 Turret Parallel|Official|FinishBeforeTurnGoal", 1217},
        {"Dream 2C|3 Turret Parallel|Official|GhostShotHitGoal", 1218},
        {"Dream 2D|1 Panic Rooms|Official|AllWizardsFullHealthGoal", 1219},
        {"Dream 2D|1 Panic Rooms|Official|GhostShotHitGoal", 1220},
        {"Dream 2D|3 The Race|Official|AllWizardsFullHealthGoal", 1221},
        {"Dream 2D|3 The Race|Official|GhostShotHitGoal", 1222},
        {"Dream 2D|3 The Race|Official|FinishBeforeTurnGoal", 1223},
        {"Dream 2D|4 Fire Closet|Official|ClearEnemiesByTurnGoal", 1224},
        {"Dream 2D|4 Fire Closet|Official|ResurrectEnemiesGoal", 1225},
        {"Dream 2D|4 Fire Closet|Official|AllWizardsAliveGoal", 1226},
        {"Dream 3B|1 Judas Priests|Official|ClearEnemiesByTurnGoal", 1227},
        {"Dream 3B|1 Judas Priests|Official|ResurrectEnemiesGoal", 1228},
        {"Dream 3B|1 Judas Priests|Official|TakeDamageGoal", 1229},
        {"Dream 3B|2 Armoured Escort|Official|OnlyDallTakeDamageGoal", 1230},
        {"Dream 3B|2 Armoured Escort|Official|DeathsDoorTotalGoal", 1231},
        {"Dream 3B|3 Three Doors|Official|GhostShotHitGoal", 1232},
        {"Dream 3B|3 Three Doors|Official|OnlyDallTakeDamageGoal", 1233},
        {"Dream 3C|1 The Cavalry|Official|AllWizardsFullHealthGoal", 1234},
        {"Dream 3C|1 The Cavalry|Official|DontSealDoorsGoal", 1235},
        {"Dream 3C|2 Reactor Recruiter|Official|ResurrectEnemiesGoal", 1236},
        {"Dream 3C|2 Reactor Recruiter|Official|RabidDamageGoal", 1237},
        {"Dream 3C|3 Push and Pull|Official|DefenestratePercentageGoal", 1238},
        {"Dream 3C|3 Push and Pull|Official|DefenestrateWithPullGoal", 1239},
        {"Dream 4A|1 Tough Cookie|Official|SporeBombDamageGoal", 1240},
        {"Dream 4A|1 Tough Cookie|Official|PriestTotalKnockbackGoal", 1241},
        {"Dream 4A|1 Tough Cookie|Official|AllWizardsFullHealthGoal", 1242},
        {"Dream 4A|2 Rocket Alley|Official|FinishBeforeTurnGoal", 1243},
        {"Dream 4A|2 Rocket Alley|Official|TakeDamageGoal", 1244},
        {"Dream 4A|2 Rocket Alley|Official|AllWizardsAliveGoal", 1245},
        {"Dream 4A|3 Fortress|Official|PreventReinforcementsGoal", 1246},
        {"Dream 4A|3 Fortress|Official|DontSealDoorsGoal", 1247},
        {"Dream 4A|3 Fortress|Official|DeathsDoorTotalGoal", 1248},
        {"Dream Heatsig|1 Warlocks in the Airlock|Official|UnsteadyKnockbackGoal", 1249},
        {"Dream Heatsig|1 Warlocks in the Airlock|Official|DontSealDoorsGoal", 1250},
        {"Dream Heatsig|1 Warlocks in the Airlock|Official|DefenestrateWarlockGoal", 1251},
        {"Dream Heatsig|2 Sabotage|Official|ChargeDamageGoal", 1252},
        {"Dream Heatsig|2 Sabotage|Official|FinishBeforeTurnGoal", 1253},
        {"Dream Heatsig|2 Sabotage|Official|GlobbedDamageGoal", 1254},
        {"Dream Heatsig|3 Escape Velocity|Official|AllWizardsFullHealthGoal", 1255},
        {"Dream Heatsig|3 Escape Velocity|Official|TakeDamageGoal", 1256},
        {"Dream Heatsig|3 Escape Velocity|Official|ResurrectEnemiesGoal", 1257},
        {"Dream Intro|1 Warlock|Official|DefenestrateInOneTurnGoal", 1258},
        {"Evidence Boss|1 The Traffic Warlock|Official|AllWizardsFullHealthGoal", 1259},
        {"Evidence Boss|1 The Traffic Warlock|Official|DefenestrateWarlockGoal", 1260},
        {"Evidence Lockup|1 Lobby|Official|AllWizardsFullHealthGoal", 1261},
        {"Evidence Lockup|1 Lobby|Official|DefenestrateWithGaleGoal", 1262},
        {"Evidence Lockup|2 Pillars|Official|ClearEnemiesByTurnGoal", 1263},
        {"Evidence Lockup|2 Pillars|Official|SingleWizardActionsInOneTurnGoal", 1264},
        {"Evidence Lockup|3 Corridors|Official|DefenestrateInOneTurnGoal", 1265},
        {"Evidence Lockup|3 Corridors|Official|PredictiveShotGoal", 1266},
        {"Exit Strategy|1 Entry Strategy|Official|FinishBeforeTurnGoal", 1267},
        {"Exit Strategy|1 Entry Strategy|Official|AbilitiesInOneTurnGoal", 1268},
        {"Exit Strategy|2 Heavies|Official|FinishBeforeTurnGoal", 1269},
        {"Exit Strategy|2 Heavies|Official|UnsteadyKnockbackGoal", 1270},
        {"Exit Strategy|2 Heavies|Official|SingleWizardActionsInOneTurnGoal", 1271},
        {"Exit Strategy|3 Neutralisers|Official|FinishBeforeTurnGoal", 1272},
        {"Exit Strategy|3 Neutralisers|Official|PreventReinforcementsGoal", 1273},
        {"Exit Strategy|3 Neutralisers|Official|ScapegoatDamageGoal", 1274},
        {"Exit Strategy|4 Junction|Official|DefenestrateInOneTurnGoal", 1275},
        {"Exit Strategy|4 Junction|Official|PreventReinforcementsGoal", 1276},
        {"Finale - Mines|1 Dust To Dust|Official|DeathsFloorDistanceGoal", 1277},
        {"Finale - Mines|1 Dust To Dust|Official|RabidBiteDistanceGoal", 1278},
        {"Finale - Mines|2 The Motherlode|Official|SaveAlliesBanksGoal", 1279},
        {"Finale - Mines|2 The Motherlode|Official|TotalBrittleDamageGoal", 1280},
        {"Finale - Roof|1 Vesker s Landing|Official|FinishBeforeTurnGoalSeer", 1281},
        {"Finale - Roof|2 The Black Ops Chronomancer|Official|PredictiveShotFinaleGoal", 1282},
        {"Finale - Roof|2 The Black Ops Chronomancer|Official|ScapegoatFinaleGoal", 1283},
        {"Finale - Roof|2 The Black Ops Chronomancer|Official|SporeBombFinaleGoal", 1284},
        {"Finale - Roof|2 The Black Ops Chronomancer|Official|ChainShockFinaleGoal", 1285},
        {"Finale - Roof|2 The Black Ops Chronomancer|Official|SwapFinaleGoal", 1286},
        {"Finale - Vault|1 The Gold Vault|Official|FinishBeforeTurnGoal", 1287},
        {"Finale - Vault|1 The Gold Vault|Official|ChargeDamageGoal", 1288},
        {"Finale - Vault|2 The Drop|Official|DontKillWarlockGoal", 1289},
        {"Finale - Vault|2 The Drop|Official|RiotBlockDamageGoal", 1290},
        {"Fort Osprey|1 Empty Coffins|Official|NoEnemiesFireGoal", 1291},
        {"Fort Osprey|1 Empty Coffins|Official|SporeBombDamageGoal", 1292},
        {"Fort Osprey|2 Cold Storage|Official|GlobbedDamageGoal", 1293},
        {"Fort Osprey|2 Cold Storage|Official|PriestTotalKnockbackGoal", 1294},
        {"Fort Osprey|3 Shield Generators|Official|FinishBeforeTurnGoal", 1295},
        {"Fort Osprey|3 Shield Generators|Official|ScapegoatDamageGoal", 1296},
        {"Fort Osprey|4 Fortified|Official|FinishBeforeTurnGoal", 1297},
        {"Fort Osprey|4 Fortified|Official|AbilitiesInOneTurnGoal", 1298},
        {"Fort Osprey|4 Fortified|Official|SporeBombDamageGoal", 1299},
        {"Kalan Ambush|1 Tick Tock|Official|ScapegoatDamageGoal", 1300},
        {"Kalan Ambush|1 Tick Tock|Official|FinishBeforeTurnGoal", 1301},
        {"Kalan Ambush|1 Tick Tock|Official|OnlyDallTakeDamageGoal", 1302},
        {"Liboli Intro|1 Twin Turrets|Official|PreventReinforcementsGoal", 1303},
        {"Liboli Intro|1 Twin Turrets|Official|FinishBeforeTurnGoal", 1304},
        {"Liboli Intro|2 Mainframe|Official|FinishBeforeTurnGoal", 1305},
        {"Liboli Intro|2 Mainframe|Official|AllWizardsFullHealthGoal", 1306},
        {"Liboli Intro|3 Heavy Duty|Official|FinishBeforeTurnGoal", 1307},
        {"Liboli Intro|3 Heavy Duty|Official|PredictiveShotGoal", 1308},
        {"Liboli Intro|4 The Cell|Official|FinishBeforeTurnGoal", 1309},
        {"Liboli Intro|4 The Cell|Official|PredictiveShotGoal", 1310},
        {"Lucid Dream - Banks|3 The Kill Zone|Official|ScapegoatDamageGoal", 1311},
        {"Lucid Dream - Banks|4 Circle Of Death|Official|DefenestrateWithPullGoal", 1312},
        {"Lucid Dream - Banks|4 Circle Of Death|Official|PriestTotalKnockbackGoal", 1313},
        {"Lucid Dream - Banks|4 Circle Of Death|Official|UnsteadyKnockbackGoal", 1314},
        {"Lucid Dream - Banks|5 Resurrection Race|Official|DeathsDoorTotalGoal", 1315},
        {"Lucid Dream - Dall|1 Blind Faith|Official|FinishBeforeTurnGoalPriest", 1316},
        {"Lucid Dream - Dall|2 The Hotspot|Official|SwapPanicShotGoal", 1317},
        {"Lucid Dream - Dall|3 Tunnel Rats|Official|RiotBlockDamageGoal", 1318},
        {"Lucid Dream - Dall|4 Unstoppable Force|Official|DontSealDoorsGoal", 1319},
        {"Lucid Dream - Jen|1 Backdoor|Official|DefenestrateInOneTurnGoal", 1320},
        {"Lucid Dream - Jen|2 No Problem|Official|DefenestratePercentageGoal", 1321},
        {"Lucid Dream - Jen|3 High Achiever|Official|FinishBeforeTurnGoal", 1322},
        {"Lucid Dream - Jen|4 Another Steve|Official|WarlockKillWarlockGoal", 1323},
        {"Lucid Dream - Rion|1 The Pit|Official|DefenestrateWithPullGoal", 1324},
        {"Lucid Dream - Rion|2 Arguably You Let The Dogs Out|Official|RabidDamageGoal", 1325},
        {"Lucid Dream - Rion|3 Anger Management|Official|SporeBombDamageGoal", 1326},
        {"Lucid Dream - Zan|1 Unsupportive Fire|Official|AllWizardsFullHealthGoal", 1327},
        {"Lucid Dream - Zan|2 Beam Flower|Official|FinishBeforeTurnGoalSeer", 1328},
        {"Lucid Dream - Zan|3 Mind Maze|Official|SingleWizardActionsInOneTurnGoal", 1329},
        {"Lucid Dream - Zan|4 Bad Zan|Official|PreventReinforcementsGoal", 1330},
        {"Proving Ground 1|1 The Clinic|Official|ProvingGroundsCondidenceGoalNavySeer", 1331},
        {"Proving Ground 1|1 The Clinic|Official|ProvingGroundsCondidenceGoalWitchCop", 1332},
        {"Proving Ground 1|1 The Clinic|Official|ProvingGroundsCondidenceGoalNecroMedic", 1333},
        {"Proving Ground 1|1 The Clinic|Official|ProvingGroundsCondidenceGoalRiotPriest", 1334},
        {"Proving Ground 1|1 The Clinic|Official|ProvingGroundsCondidenceGoalDruid", 1335},
        {"Proving Ground 2|1 The Cooker|Official|ProvingGroundsCondidenceGoalNavySeer", 1336},
        {"Proving Ground 2|1 The Cooker|Official|ProvingGroundsCondidenceGoalWitchCop", 1337},
        {"Proving Ground 2|1 The Cooker|Official|ProvingGroundsCondidenceGoalNecroMedic", 1338},
        {"Proving Ground 2|1 The Cooker|Official|ProvingGroundsCondidenceGoalRiotPriest", 1339},
        {"Proving Ground 2|1 The Cooker|Official|ProvingGroundsCondidenceGoalDruid", 1340},
        {"Proving Ground 3|1 The Wall|Official|ProvingGroundsCondidenceGoalNavySeer", 1341},
        {"Proving Ground 3|1 The Wall|Official|ProvingGroundsCondidenceGoalWitchCop", 1342},
        {"Proving Ground 3|1 The Wall|Official|ProvingGroundsCondidenceGoalNecroMedic", 1343},
        {"Proving Ground 3|1 The Wall|Official|ProvingGroundsCondidenceGoalRiotPriest", 1344},
        {"Proving Ground 3|1 The Wall|Official|ProvingGroundsCondidenceGoalDruid", 1345},
        {"Proving Ground 4|1 The Tank|Official|ProvingGroundsCondidenceGoalNavySeer", 1346},
        {"Proving Ground 4|1 The Tank|Official|ProvingGroundsCondidenceGoalWitchCop", 1347},
        {"Proving Ground 4|1 The Tank|Official|ProvingGroundsCondidenceGoalNecroMedic", 1348},
        {"Proving Ground 4|1 The Tank|Official|ProvingGroundsCondidenceGoalRiotPriest", 1349},
        {"Proving Ground 4|1 The Tank|Official|ProvingGroundsCondidenceGoalDruid", 1350},
        {"Siege Cleric|1 The Siege Cleric|Official|PreventReinforcementsGoal", 1351},
        {"Siege Cleric|1 The Siege Cleric|Official|FinishBeforeTurnGoal", 1352},
        {"Siege Cleric|1 The Siege Cleric|Official|PriestTotalKnockbackGoal", 1353},
        {"Siege Cleric|2 The Other Three Siege Clerics|Official|ResurrectAllyGoal", 1354},
        {"Siege Cleric|2 The Other Three Siege Clerics|Official|TotalBrittleDamageGoal", 1355},
        {"Streets|1 Downtown|Official|GhostShotHitGoal", 1356},
        {"Streets|1 Downtown|Official|FinishBeforeTurnGoal", 1357},
        {"Streets|1 Downtown|Official|NoEnemiesFireGoal", 1358},
        {"Streets|2 Curfew|Official|GhostShotHitGoal", 1359},
        {"Streets|2 Curfew|Official|DefenestrateInOneTurnGoal", 1360},
        {"Streets|2 Curfew|Official|PriestTotalKnockbackGoal", 1361},
        {"Streets|3 Going To Ground|Official|PreventReinforcementsGoal", 1362},
        {"Streets|3 Going To Ground|Official|FinishBeforeTurnGoal", 1363},
        {"Streets|3 Going To Ground|Official|ChargeDamageGoal", 1364},
        {"The Broadcast|1 Heavy Backup|Official|PreventReinforcementsGoal", 1365},
        {"The Broadcast|1 Heavy Backup|Official|DestroyMoreCachesGoal", 1366},
        {"The Broadcast|2 Tipping Point|Official|ScapegoatDamageGoal", 1367},
        {"The Broadcast|2 Tipping Point|Official|WitchTotalKnockbackGoal", 1368},
        {"The Broadcast|3 Firewall|Official|PreventReinforcementsGoal", 1369},
        {"The Broadcast|3 Firewall|Official|HitRiotBlockGoal", 1370},
        {"The Broadcast|4 Caught In Traffic|Official|FinishBeforeTurnGoal", 1371},
        {"The Broadcast|4 Caught In Traffic|Official|ScapegoatDamageGoal", 1372},
        {"The Broadcast|5 The Armoury|Official|DestroyCachesByTurnGoal", 1373},
        {"The Broadcast|5 The Armoury|Official|AllWizardsAliveGoal", 1374},
        {"The Broadcast|5 The Armoury|Official|ResurrectEnemiesGoal", 1375},
        {"The Broadcast|5 The Armoury|Official|ClearEnemiesByTurnGoal", 1376},
        {"The Meet|1 Spectral Skull|Official|FinishBeforeTurnGoal", 1377},
        {"The Meet|1 Spectral Skull|Official|GhostShotHitGoal", 1378},
        {"The Meet|1 Spectral Skull|Official|AbilitiesInOneTurnGoal", 1379},
        {"The Meet|2 Officers|Official|ClearEnemiesByTurnGoal", 1380},
        {"The Meet|2 Officers|Official|GhostShotHitGoal", 1381},
        {"The Meet|3 Reaching The Meet|Official|FinishBeforeTurnGoal", 1382},
        {"The Meet|3 Reaching The Meet|Official|ScapegoatDamageGoal", 1383},
        {"The Pyromancer|1 The Less Lethal Pyromancer|Official|DeathsDoorWarlockGoal", 1384},
        {"The Pyromancer|1 The Less Lethal Pyromancer|Official|AbilitiesInOneTurnGoal", 1385},
        {"The Pyromancer|1 The Less Lethal Pyromancer|Official|ResurrectAllyGoal", 1386},
        {"The Recording|1 The Golden Arms|Official|AllWizardsFullHealthGoal", 1387},
        {"The Recording|1 The Golden Arms|Official|DestroyMoreCachesGoal", 1388},
        {"The Recording|1 The Golden Arms|Official|ClearEnemiesByTurnGoal", 1389},
        {"The Recording|2 Protection Ring|Official|GhostShotHitGoal", 1390},
        {"The Recording|2 Protection Ring|Official|DefenestrateInOneTurnGoal", 1391},
        {"The Recording|2 Protection Ring|Official|AbilitiesInOneTurnGoal", 1392},
        {"The Recording|3 The Dead Drop|Official|DestroyCachesByTurnGoal", 1393},
        {"The Recording|4 The Stand|Official|SurviveTurnsConfidenceGoalNavySeer", 1394},
        {"The Recording|4 The Stand|Official|SurviveTurnsConfidenceGoalWitchCop", 1395},
        {"The Recording|4 The Stand|Official|SurviveTurnsConfidenceGoalNecroMedic", 1396},
        {"The Recording|4 The Stand|Official|SurviveTurnsConfidenceGoalRiotPriest", 1397},
        {"Train|1 On Board|Official|AllWizardsFullHealthGoal", 1398},
        {"Train|1 On Board|Official|GhostShotHitGoal", 1399},
        {"Train|2 Sappers|Official|FinishBeforeTurnGoal", 1400},
        {"Train|3 The Shepherd|Official|AllWizardsFullHealthGoal", 1401},
        {"Train|3 The Shepherd|Official|UnsteadyKnockbackGoal", 1402},
        {"Train|4 Terminal|Official|DefenestrateInOneTurnGoal", 1403},
        {"Train|5 The Riot Priest|Official|DeathsDoorTotalGoal", 1404},
        {"Train|5 The Riot Priest|Official|AllWizardsAliveGoal", 1405},
        {"Train|5 The Riot Priest|Official|DefenestrateInOneTurnGoal", 1406},
        {"Two Trains|1 Gangway|Official|BroomDefenestrationGoal", 1407},
        {"Two Trains|1 Gangway|Official|SporeBombDamageGoal", 1408},
        {"Two Trains|2 Barrier Drones|Official|ClearEnemiesByTurnGoal", 1409},
        {"Two Trains|2 Barrier Drones|Official|SporeBombDamageGoal", 1410},
        {"Two Trains|3 Chasers|Official|ScapegoatDamageGoal", 1411},
        {"Two Trains|3 Chasers|Official|RabidDamageGoal", 1412},
        {"Two Trains|4 Sabotage|Official|PlantBombByEndOfTurnGoal", 1413},
        {"Two Trains|4 Sabotage|Official|ChargeDamageGoal", 1414},
        {"Two Trains|5 Countdown|Official|PriestTotalKnockbackGoal", 1415},
        {"Two Trains|5 Countdown|Official|DefenestrateBeforeTurnGoal", 1416},
        {"Villa Medil|1 Split Focus|Official|FinishBeforeTurnGoal", 1417},
        {"Villa Medil|1 Split Focus|Official|DefenestrateWithPullGoal", 1418},
        {"Villa Medil|2 Locked Out|Official|PreventReinforcementsGoal", 1419},
        {"Villa Medil|3 Desk Job|Official|ScapegoatDamageGoal", 1420},
        {"Villa Medil|3 Desk Job|Official|FinishBeforeTurnGoal", 1421},
        {"Villa Medil|4 Time Pressure|Official|DontSealDoorsGoal", 1422},
        {"Villa Medil|4 Time Pressure|Official|ClearEnemiesByTurnGoal", 1423},
        {"Villa Medil|5 The Stone Table|Official|SporeBombDamageGoal", 1424},
        {"Villa Medil|5 The Stone Table|Official|OnlyDallTakeDamageGoal", 1425},
        {"Villa Medil|5 The Stone Table|Official|SedativeDamageGoal", 1426},
        {"Necro Intro|1 Intro|Official|DeathsDoorTotalGoal", 1427},
        {"Necro Intro|1 Intro|Official|FinishBeforeTurnGoal", 1428},
        {"Necro Intro|2 Lead Medicine|Official|FinishBeforeTurnGoal", 1429},
        {"Necro Intro|3 Broom Breach|Official|FinishBeforeTurnGoal", 1430},
        {"Necro Intro|3 Broom Breach|Official|DeathsDoorTotalGoal", 1431},
    };
}